ALTER TABLE "Campaign" ADD COLUMN IF NOT EXISTS "archivedAt" TIMESTAMP(3);
ALTER TABLE "DistributionList" ADD COLUMN IF NOT EXISTS "archivedAt" TIMESTAMP(3);
ALTER TABLE "DistributionList" ADD COLUMN IF NOT EXISTS "posterImageAssetId" TEXT;
ALTER TABLE "DistributionListItem" ADD COLUMN IF NOT EXISTS "includePermitForm" BOOLEAN DEFAULT false;
ALTER TABLE "DistributionListItem" ADD COLUMN IF NOT EXISTS "includePosterImage" BOOLEAN DEFAULT false;
ALTER TABLE "City" ADD COLUMN IF NOT EXISTS "requiresPermitForm" BOOLEAN DEFAULT false;
ALTER TABLE "City" ADD COLUMN IF NOT EXISTS "permitFormAssetId" TEXT;
CREATE TABLE IF NOT EXISTS "FileAsset" (
  "id" TEXT PRIMARY KEY,
  "key" TEXT NOT NULL UNIQUE,
  "fileName" TEXT NOT NULL,
  "contentType" TEXT NOT NULL,
  "size" INTEGER NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
